export const LEGAL_DOCUMENTS = ['privacy', 'terms', 'billing'] as const;
export type LegalDocumentId = (typeof LEGAL_DOCUMENTS)[number];
export type LegalLocale = 'en' | 'fr' | 'ar';

type LegalSection = { title: string; paragraphs: readonly string[]; items?: readonly string[] };
type LegalDocument = {
  label: string;
  title: string;
  description: string;
  updated: string;
  sections: readonly LegalSection[];
};

export const legalUi: Record<LegalLocale, { back: string; updated: string; navigation: string }> = {
  en: { back: 'Back to VANTRA', updated: 'Last updated', navigation: 'Legal navigation' },
  fr: { back: 'Retour à VANTRA', updated: 'Dernière mise à jour', navigation: 'Navigation juridique' },
  ar: { back: 'العودة إلى VANTRA', updated: 'آخر تحديث', navigation: 'التنقل القانوني' },
};

export const legalContent: Record<LegalLocale, Record<LegalDocumentId, LegalDocument>> = {
  en: {
    privacy: {
      label: 'Privacy',
      title: 'Privacy Policy',
      description: 'How VANTRA collects, uses, protects, and manages personal information.',
      updated: 'September 8, 2026',
      sections: [
        { title: '1. Scope', paragraphs: ['This Privacy Policy applies when you visit VANTRA, create an account, sign in, or use VANTRA services. It explains the categories of information we process, why we process them, and the choices available to you.'] },
        { title: '2. Information we collect', paragraphs: ['We collect only information reasonably needed to operate, secure, and improve VANTRA.'], items: ['Account data, such as your name, email address, account identifier, profile details, and authentication status.', 'When you use Google Sign-In, information Google makes available with your permission, such as your name, email address, profile image, and Google account identifier. VANTRA does not receive your Google password.', 'Essential cookie and session information used to keep you signed in, remember language preferences, protect sessions, and maintain service continuity.', 'Usage and security information, such as device and browser information, IP address, timestamps, feature interactions, diagnostic logs, and suspected abuse or fraud signals.', 'AI prompts, chat messages, uploaded files, reference media, generated content, and related settings when you choose to submit or save them.'] },
        { title: '3. How we use information', paragraphs: ['We use information to provide and personalize the service, authenticate users, process requested AI tasks, maintain saved work where enabled, provide support, monitor reliability, prevent fraud and abuse, comply with legal obligations, and improve VANTRA. We do not use Google Sign-In data for purposes unrelated to authentication and account operation.'] },
        { title: '4. AI content and service providers', paragraphs: ['When you request an AI feature, relevant prompts, uploads, and settings may be transmitted to service providers that process the request on VANTRA’s behalf. We disclose only what is reasonably necessary for that purpose, and their processing is subject to applicable terms and legal obligations. Do not submit confidential, sensitive, or legally restricted material unless you are authorized to do so.'] },
        { title: '5. Sharing and disclosure', paragraphs: ['We may share information with vendors that support hosting, authentication, security, analytics, customer support, payment processing when offered, and AI processing. We may also disclose information when required by law, to protect users or the service, or as part of a business reorganization. VANTRA does not sell personal information for money.'] },
        { title: '6. Retention and deletion', paragraphs: ['We retain information only for as long as reasonably necessary for the purposes described here, including providing the service, maintaining security and audit records, resolving disputes, and meeting legal obligations. Retention periods vary by data type and account activity. You may request deletion of your account or personal information. Some information may remain temporarily in backups or be retained where required for security, fraud prevention, accounting, or law.'] },
        { title: '7. Security', paragraphs: ['We use reasonable technical and organizational safeguards designed to protect personal information. No system is completely secure, and VANTRA cannot guarantee that unauthorized access, loss, or misuse will never occur. You are responsible for protecting your credentials and notifying us of suspected account compromise.'] },
        { title: '8. Your rights and choices', paragraphs: ['Depending on applicable law, you may have rights to access, correct, delete, restrict, or object to certain processing; request a portable copy of information; withdraw consent where processing relies on consent; or complain to a competent authority. We may need to verify your identity before fulfilling a request. You can also manage language and session preferences through the service or browser.'] },
        { title: '9. Changes and contact', paragraphs: ['We may update this policy as VANTRA evolves. Material changes will be communicated through an appropriate notice where required. For privacy questions or requests, contact privacy@joinvantra.com.'] },
      ],
    },
    terms: {
      label: 'Terms',
      title: 'Terms of Service',
      description: 'The rules that apply when you access or use VANTRA.',
      updated: 'September 8, 2026',
      sections: [
        { title: '1. Acceptance and eligibility', paragraphs: ['By accessing or using VANTRA, you agree to these Terms. If you use VANTRA on behalf of another person or organization, you confirm that you are authorized to bind them. You must be legally able to enter into this agreement under applicable law.'] },
        { title: '2. Accounts', paragraphs: ['You must provide accurate information, keep your credentials secure, and promptly notify VANTRA of suspected unauthorized access. You are responsible for activity under your account except to the extent caused by VANTRA’s breach of applicable obligations. Accounts may not be sold, transferred, or shared in a way that compromises security or violates these Terms.'] },
        { title: '3. AI services and accuracy', paragraphs: ['VANTRA provides access to AI-assisted chat, image, video, and related tools as they become available. AI output may be inaccurate, incomplete, biased, offensive, or unsuitable for your purpose. It is not professional, legal, medical, financial, or other expert advice. You must independently review output before relying on, publishing, or acting on it. VANTRA does not guarantee any particular result, model availability, response time, or uninterrupted service.'] },
        { title: '4. Your content and generated content', paragraphs: ['You retain rights you already hold in content you submit. You grant VANTRA a limited, worldwide license to host, process, reproduce, transmit, and display that content only as needed to provide, secure, and improve the service or comply with law. As between you and VANTRA, and to the extent permitted by law, you may use generated content subject to these Terms and any applicable third-party restrictions. Because laws concerning AI output vary, VANTRA does not guarantee that generated content is protectable, unique, non-infringing, or available for exclusive ownership.'] },
        { title: '5. Prohibited use', paragraphs: ['You may not use VANTRA to violate law or third-party rights; create or distribute malware; exploit, harm, or deceive people; generate unlawful sexual or violent content; impersonate others; facilitate fraud; evade safeguards; interfere with the service; probe systems without authorization; scrape or resell the service except with written permission; or submit content you lack the right to use.'] },
        { title: '6. Service and provider changes', paragraphs: ['VANTRA may add, change, suspend, or remove features, models, providers, limits, or access methods. Third-party providers may change or discontinue their services without VANTRA’s control. We may perform maintenance or experience outages, delays, capacity constraints, or data loss. Where practical, we will try to provide notice of material changes, but urgent security, legal, or provider changes may take effect immediately.'] },
        { title: '7. Suspension and termination', paragraphs: ['VANTRA may restrict, suspend, or terminate access when reasonably necessary to address violations, security risks, fraud, non-payment, legal requirements, harm to users or third parties, or material operational risk. You may stop using VANTRA at any time. Provisions that by their nature should survive termination will remain in effect.'] },
        { title: '8. Intellectual property', paragraphs: ['VANTRA and its licensors retain all rights in the service, software, interface, branding, documentation, and other materials, excluding your content. These Terms do not grant rights to VANTRA names, logos, or technology except the limited right to use the service as authorized. Feedback may be used without restriction or compensation, provided it does not identify you publicly without permission.'] },
        { title: '9. Disclaimers', paragraphs: ['To the maximum extent permitted by applicable law, VANTRA is provided “as is” and “as available.” VANTRA disclaims implied warranties, including merchantability, fitness for a particular purpose, non-infringement, and warranties arising from course of dealing. Nothing in these Terms excludes rights or warranties that cannot legally be excluded.'] },
        { title: '10. Limitation of liability', paragraphs: ['To the maximum extent permitted by applicable law, VANTRA will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenue, data, goodwill, or business opportunities. VANTRA’s aggregate liability arising from the service will not exceed the amount you paid to VANTRA during the 12 months before the event giving rise to the claim, or any higher minimum liability required by applicable law.'] },
        { title: '11. Force majeure', paragraphs: ['VANTRA is not responsible for delay or failure caused by events beyond reasonable control, including natural disasters, internet or utility failures, cyberattacks, labor disputes, governmental actions, war, civil unrest, epidemics, or failures of third-party infrastructure or providers.'] },
        { title: '12. Changes to these Terms', paragraphs: ['We may update these Terms to reflect service, legal, security, or operational changes. Updated Terms will be posted with a revised date. Where required, we will give additional notice or request renewed consent. Continued use after an update takes effect means you accept the revised Terms, except where applicable law requires another form of agreement.'] },
      ],
    },
    billing: {
      label: 'Billing',
      title: 'Billing, Subscriptions & Credits Policy',
      description: 'How paid plans, renewals, cancellations, refunds, and VANTRA credits work when offered.',
      updated: 'September 8, 2026',
      sections: [
        { title: '1. Scope and checkout disclosures', paragraphs: ['This policy applies to paid subscriptions, credit purchases, and other paid VANTRA services when they are offered. The price, currency, billing period, included credits, usage limits, taxes, and any renewal terms shown at checkout form part of your purchase. If a paid feature is not yet available, this policy does not make it available.'] },
        { title: '2. Subscriptions and renewals', paragraphs: ['A subscription begins when payment is accepted. If checkout states that a subscription renews automatically, it will renew for the disclosed period at the then-applicable price until cancelled. VANTRA will provide renewal information and notices required by applicable law. You are responsible for keeping payment information current.'] },
        { title: '3. Cancellation', paragraphs: ['You may cancel an active subscription through the available account controls or support channel. Unless checkout or applicable law states otherwise, cancellation stops future renewals and takes effect at the end of the current paid period; access and included benefits may continue until then. Deleting an account does not automatically resolve outstanding charges or disputes.'] },
        { title: '4. VANTRA credits', paragraphs: ['Credits are a limited contractual right to use eligible VANTRA features. They are not money, stored value, a bank balance, or a transferable asset, and they have no cash value except where required by law. The service may display an estimated or verified credit cost before a request. Actual consumption may depend on the selected model, media type, settings, or result. Your available credit balance is the balance displayed in your account.'] },
        { title: '5. Failed or cancelled generations', paragraphs: ['VANTRA generally does not intend to charge credits for a generation that fails before producing a usable result. A temporary reservation may appear while processing and should be released or reconciled after failure or cancellation. If credits remain deducted because of a technical error, you may request review. Abuse, repeated intentional cancellation, or provider costs already incurred may be handled as disclosed for the relevant feature and as permitted by law.'] },
        { title: '6. Refunds', paragraphs: ['Payments are generally final after credits or paid service benefits have been used, except where required by applicable law or where VANTRA expressly offers a refund. Refund eligibility may consider service delivery, usage, duplicate charges, technical failure, fraud, and the payment method’s rules. Nothing in this policy limits mandatory consumer rights.'] },
        { title: '7. Price and limit changes', paragraphs: ['VANTRA may change future prices, credit costs, plan features, or usage limits. Changes will not retroactively alter a completed purchase unless required by law or needed to correct an obvious error. Changes affecting an automatic renewal will be communicated in advance where required, and you may cancel before the new terms take effect.'] },
        { title: '8. Failed payments, chargebacks, and fraud', paragraphs: ['If payment fails, VANTRA may retry the charge where authorized, restrict paid features, or suspend the subscription. Contact VANTRA before initiating a chargeback so we can investigate. Fraudulent payments, abusive chargebacks, payment circumvention, or misuse of credits may result in suspension, reversal of improperly obtained credits, collection of amounts lawfully owed, or reporting to relevant payment or legal authorities.'] },
        { title: '9. Unused credits', paragraphs: ['Expiration, rollover, and allocation rules for unused credits are the rules displayed for the relevant plan or purchase at checkout. Unless expressly stated otherwise, credits are non-transferable and cannot be exchanged for cash. VANTRA will not invent or silently change an expiration rule after purchase, subject to service changes required by law or this policy.'] },
        { title: '10. Permanent shutdown', paragraphs: ['If VANTRA permanently discontinues a paid service, we will make reasonable efforts to provide advance notice where feasible. Treatment of unused paid service time or purchased credits will follow the applicable checkout terms and mandatory law, and may include continued access for a wind-down period, replacement value, account credit, or refund where required.'] },
      ],
    },
  },
  fr: {
    privacy: { label: 'Confidentialité', title: 'Politique de confidentialité', description: 'Comment VANTRA collecte, utilise, protège et gère vos informations personnelles.', updated: '8 septembre 2026', sections: [
      { title: '1. Champ d’application', paragraphs: ['Cette politique s’applique lorsque vous consultez VANTRA, créez un compte, vous connectez ou utilisez nos services. Elle explique les données traitées, leurs finalités et vos choix.'] },
      { title: '2. Informations collectées', paragraphs: ['Nous collectons uniquement les informations raisonnablement nécessaires au fonctionnement, à la sécurité et à l’amélioration de VANTRA.'], items: ['Données de compte : nom, adresse e-mail, identifiant de compte, profil et état d’authentification.', 'Avec Google Sign-In : les informations que Google partage avec votre autorisation, notamment votre nom, adresse e-mail, photo de profil et identifiant Google. VANTRA ne reçoit pas votre mot de passe Google.', 'Cookies et données de session indispensables à la connexion, aux préférences linguistiques, à la sécurité et à la continuité du service.', 'Données d’utilisation et de sécurité : appareil, navigateur, adresse IP, horodatages, interactions, journaux de diagnostic et signaux de fraude ou d’abus.', 'Prompts, messages, fichiers importés, médias de référence, contenus générés et réglages lorsque vous choisissez de les transmettre ou de les enregistrer.'] },
      { title: '3. Utilisation des informations', paragraphs: ['Nous utilisons ces informations pour fournir et personnaliser le service, authentifier les utilisateurs, exécuter les tâches IA demandées, conserver le travail lorsque cette option est activée, assister les utilisateurs, surveiller la fiabilité, prévenir la fraude et les abus, respecter nos obligations et améliorer VANTRA. Les données Google Sign-In ne sont pas utilisées à des fins étrangères à l’authentification et au fonctionnement du compte.'] },
      { title: '4. Contenu IA et prestataires', paragraphs: ['Lors d’une demande IA, les prompts, fichiers et réglages utiles peuvent être transmis à des prestataires qui traitent la demande pour VANTRA. Nous ne communiquons que ce qui est raisonnablement nécessaire et exigeons un traitement conforme aux obligations contractuelles et légales applicables. Ne transmettez pas de contenu confidentiel, sensible ou réglementé sans autorisation.'] },
      { title: '5. Partage et divulgation', paragraphs: ['Nous pouvons partager des informations avec les prestataires nécessaires à l’hébergement, l’authentification, la sécurité, l’analyse, l’assistance, au paiement lorsqu’il sera proposé et au traitement IA. Une divulgation peut aussi intervenir si la loi l’exige, pour protéger les utilisateurs ou le service, ou lors d’une réorganisation. VANTRA ne vend pas vos données personnelles contre rémunération.'] },
      { title: '6. Conservation et suppression', paragraphs: ['Nous conservons les informations pendant la durée raisonnablement nécessaire aux finalités décrites, notamment le service, la sécurité, les audits, les litiges et les obligations légales. La durée dépend du type de donnée et de l’activité du compte. Vous pouvez demander la suppression du compte ou de vos données. Certaines informations peuvent subsister temporairement dans les sauvegardes ou être conservées pour la sécurité, la prévention de la fraude, la comptabilité ou la loi.'] },
      { title: '7. Sécurité', paragraphs: ['Nous appliquons des mesures techniques et organisationnelles raisonnables. Aucun système n’est totalement sûr et VANTRA ne peut garantir l’absence de tout accès non autorisé, perte ou usage abusif. Vous devez protéger vos identifiants et nous signaler toute compromission présumée.'] },
      { title: '8. Vos droits et choix', paragraphs: ['Selon la loi applicable, vous pouvez demander l’accès, la rectification, la suppression, la limitation ou l’opposition à certains traitements, la portabilité, le retrait du consentement ou saisir une autorité compétente. Une vérification d’identité peut être nécessaire. Vous pouvez aussi gérer la langue et les sessions dans le service ou le navigateur.'] },
      { title: '9. Modifications et contact', paragraphs: ['Cette politique peut évoluer avec VANTRA. Les changements importants feront l’objet d’une information appropriée lorsque la loi l’exige. Pour toute question ou demande : privacy@joinvantra.com.'] },
    ] },
    terms: { label: 'Conditions', title: 'Conditions d’utilisation', description: 'Les règles applicables à l’accès et à l’utilisation de VANTRA.', updated: '8 septembre 2026', sections: [
      { title: '1. Acceptation et capacité', paragraphs: ['En accédant à VANTRA ou en l’utilisant, vous acceptez ces Conditions. Si vous agissez pour une personne ou une organisation, vous confirmez avoir l’autorité nécessaire. Vous devez avoir la capacité juridique requise par la loi applicable.'] },
      { title: '2. Comptes', paragraphs: ['Vous devez fournir des informations exactes, protéger vos identifiants et signaler rapidement tout accès suspect. Vous êtes responsable de l’activité de votre compte, sauf dans la mesure où elle résulte d’un manquement de VANTRA à ses obligations. La vente, le transfert ou le partage d’un compte compromettant la sécurité est interdit.'] },
      { title: '3. Services IA et fiabilité', paragraphs: ['VANTRA donne accès à des outils de chat, image, vidéo et services associés lorsqu’ils sont disponibles. Les résultats IA peuvent être inexacts, incomplets, biaisés, offensants ou inadaptés. Ils ne constituent pas un conseil juridique, médical, financier ou professionnel. Vous devez les vérifier avant de vous y fier, de les publier ou d’agir. Aucun résultat, modèle, délai ou fonctionnement ininterrompu n’est garanti.'] },
      { title: '4. Vos contenus et les résultats générés', paragraphs: ['Vous conservez les droits que vous détenez sur les contenus transmis. Vous accordez à VANTRA une licence limitée et mondiale pour les héberger, traiter, reproduire, transmettre et afficher uniquement afin de fournir, sécuriser et améliorer le service ou respecter la loi. Entre vous et VANTRA, et dans les limites de la loi, vous pouvez utiliser les résultats sous réserve de ces Conditions et des restrictions de tiers. VANTRA ne garantit pas qu’un résultat soit protégeable, unique, non contrefaisant ou susceptible d’une propriété exclusive.'] },
      { title: '5. Usages interdits', paragraphs: ['Il est interdit d’enfreindre la loi ou les droits de tiers, créer des logiciels malveillants, exploiter ou tromper des personnes, produire des contenus sexuels ou violents illégaux, usurper une identité, faciliter une fraude, contourner les protections, perturber le service, tester des systèmes sans autorisation, extraire ou revendre le service sans accord écrit, ou transmettre un contenu que vous n’êtes pas autorisé à utiliser.'] },
      { title: '6. Évolution du service et des prestataires', paragraphs: ['VANTRA peut ajouter, modifier, suspendre ou retirer des fonctionnalités, modèles, prestataires, limites ou méthodes d’accès. Des tiers peuvent modifier ou interrompre leurs services hors de notre contrôle. Des maintenances, pannes, retards, limites de capacité ou pertes de données peuvent survenir. Nous tenterons d’annoncer les changements importants lorsque cela est possible.'] },
      { title: '7. Suspension et résiliation', paragraphs: ['VANTRA peut limiter, suspendre ou fermer un accès pour traiter une violation, un risque de sécurité, une fraude, un impayé, une obligation légale, un préjudice ou un risque opérationnel important. Vous pouvez cesser d’utiliser VANTRA à tout moment. Les clauses qui doivent survivre par nature restent applicables.'] },
      { title: '8. Propriété intellectuelle', paragraphs: ['VANTRA et ses concédants conservent les droits sur le service, le logiciel, l’interface, la marque, la documentation et les autres éléments, hors vos contenus. Ces Conditions n’accordent aucun droit sur les noms, logos ou technologies de VANTRA au-delà de l’usage autorisé du service. Les suggestions peuvent être utilisées sans restriction ni rémunération, sans vous identifier publiquement sans permission.'] },
      { title: '9. Exclusions de garanties', paragraphs: ['Dans les limites maximales autorisées par la loi, VANTRA est fourni « en l’état » et « selon disponibilité ». Les garanties implicites, notamment de qualité marchande, d’adéquation, de non-contrefaçon ou issues des usages, sont exclues. Rien n’exclut les droits ou garanties que la loi interdit d’écarter.'] },
      { title: '10. Limitation de responsabilité', paragraphs: ['Dans les limites maximales autorisées, VANTRA ne répond pas des dommages indirects, accessoires, spéciaux, consécutifs, exemplaires ou punitifs, ni des pertes de bénéfices, revenus, données, clientèle ou opportunités. La responsabilité totale de VANTRA ne dépassera pas le montant payé à VANTRA au cours des douze mois précédant le fait générateur, ou tout minimum supérieur imposé par la loi.'] },
      { title: '11. Force majeure', paragraphs: ['VANTRA n’est pas responsable des retards ou manquements dus à des événements hors de son contrôle raisonnable : catastrophe, panne internet ou électrique, cyberattaque, conflit social, action publique, guerre, troubles, épidémie ou défaillance d’un prestataire.'] },
      { title: '12. Modification des Conditions', paragraphs: ['Ces Conditions peuvent être mises à jour pour refléter des changements de service, de droit, de sécurité ou d’exploitation. La date sera révisée et un avis supplémentaire ou un nouveau consentement sera demandé lorsque nécessaire. La poursuite de l’utilisation après leur entrée en vigueur vaut acceptation, sauf exigence légale contraire.'] },
    ] },
    billing: { label: 'Facturation', title: 'Politique de facturation, abonnements et crédits', description: 'Le fonctionnement des offres payantes, renouvellements, résiliations, remboursements et crédits VANTRA lorsqu’ils sont proposés.', updated: '8 septembre 2026', sections: [
      { title: '1. Champ d’application et informations avant achat', paragraphs: ['Cette politique s’applique aux abonnements, achats de crédits et autres services payants lorsqu’ils sont proposés. Le prix, la devise, la période, les crédits inclus, les limites, taxes et conditions de renouvellement affichés au paiement font partie de l’achat. Cette politique ne rend pas disponible une offre qui ne l’est pas encore.'] },
      { title: '2. Abonnements et renouvellements', paragraphs: ['L’abonnement commence après acceptation du paiement. Si le paiement indique un renouvellement automatique, il se poursuit pour la période annoncée au tarif alors applicable jusqu’à résiliation. VANTRA fournit les informations et avis imposés par la loi. Vous devez maintenir vos informations de paiement à jour.'] },
      { title: '3. Résiliation', paragraphs: ['Vous pouvez résilier via les contrôles de compte disponibles ou le canal d’assistance. Sauf indication contraire ou obligation légale, la résiliation bloque les renouvellements futurs et prend effet à la fin de la période payée ; les avantages peuvent rester actifs jusque-là. Supprimer le compte ne règle pas automatiquement les montants ou litiges en cours.'] },
      { title: '4. Crédits VANTRA', paragraphs: ['Les crédits constituent un droit contractuel limité d’utiliser certaines fonctions. Ce ne sont ni de l’argent, ni une valeur stockée, ni un compte bancaire, ni un actif transférable ; ils n’ont aucune valeur en espèces sauf obligation légale. Le coût estimé ou vérifié peut être affiché avant une demande et varier selon le modèle, le média, les réglages ou le résultat. Votre solde disponible est celui affiché dans votre compte.'] },
      { title: '5. Générations échouées ou annulées', paragraphs: ['VANTRA n’entend généralement pas débiter de crédits lorsqu’aucun résultat utilisable n’est produit. Une réservation temporaire peut apparaître pendant le traitement puis être libérée ou régularisée. Si des crédits restent débités à cause d’une erreur technique, vous pouvez demander un examen. Les abus, annulations intentionnelles répétées ou coûts déjà engagés peuvent être traités selon les informations de la fonction concernée et la loi.'] },
      { title: '6. Remboursements', paragraphs: ['Les paiements sont généralement définitifs après utilisation des crédits ou avantages, sauf lorsque la loi l’exige ou lorsqu’un remboursement est expressément proposé. L’éligibilité peut tenir compte de la prestation, de l’usage, des doublons, d’un incident technique, d’une fraude et des règles du moyen de paiement. Vos droits impératifs restent applicables.'] },
      { title: '7. Modification des prix et limites', paragraphs: ['VANTRA peut modifier les futurs prix, coûts en crédits, fonctions ou limites. Une modification ne change pas rétroactivement un achat terminé, sauf obligation légale ou correction d’une erreur manifeste. Les changements d’un renouvellement automatique sont annoncés à l’avance lorsque nécessaire, avec possibilité d’annuler avant leur application.'] },
      { title: '8. Paiements échoués, contestations et fraude', paragraphs: ['En cas d’échec, VANTRA peut retenter un débit autorisé, limiter les fonctions payantes ou suspendre l’abonnement. Contactez VANTRA avant une contestation bancaire afin de permettre une enquête. Fraudes, contestations abusives, contournements ou détournements de crédits peuvent entraîner suspension, retrait des crédits obtenus indûment, recouvrement légal ou signalement aux acteurs compétents.'] },
      { title: '9. Crédits inutilisés', paragraphs: ['Les règles d’expiration, de report et d’attribution sont celles affichées pour l’offre au moment du paiement. Sauf indication expresse, les crédits ne sont ni transférables ni convertibles en espèces. VANTRA n’inventera ni ne modifiera silencieusement une règle d’expiration après l’achat, sous réserve de la loi et de cette politique.'] },
      { title: '10. Arrêt définitif du service', paragraphs: ['Si VANTRA arrête définitivement un service payant, un préavis raisonnable sera fourni lorsque possible. Le traitement du temps payé ou des crédits achetés inutilisés suivra les conditions de l’achat et la loi impérative ; il pourra inclure une période de transition, une valeur de remplacement, un avoir ou un remboursement lorsque requis.'] },
    ] },
  },
  ar: {
    privacy: { label: 'الخصوصية', title: 'سياسة الخصوصية', description: 'كيف تجمع VANTRA المعلومات الشخصية وتستخدمها وتحميها وتديرها.', updated: '8 سبتمبر 2026', sections: [
      { title: '1. نطاق السياسة', paragraphs: ['تنطبق هذه السياسة عند زيارة VANTRA أو إنشاء حساب أو تسجيل الدخول أو استخدام الخدمات. وتوضح فئات المعلومات التي نعالجها وأسباب المعالجة والخيارات المتاحة لك.'] },
      { title: '2. المعلومات التي نجمعها', paragraphs: ['نجمع فقط المعلومات اللازمة بشكل معقول لتشغيل VANTRA وحمايتها وتحسينها.'], items: ['بيانات الحساب مثل الاسم والبريد الإلكتروني ومعرّف الحساب وتفاصيل الملف الشخصي وحالة المصادقة.', 'عند استخدام تسجيل الدخول عبر Google: المعلومات التي تتيحها Google بإذنك، مثل الاسم والبريد الإلكتروني وصورة الملف الشخصي ومعرّف حساب Google. لا تستلم VANTRA كلمة مرور Google الخاصة بك.', 'ملفات تعريف الارتباط وبيانات الجلسة الضرورية لتسجيل الدخول وتذكر اللغة وحماية الجلسة واستمرارية الخدمة.', 'بيانات الاستخدام والأمان مثل معلومات الجهاز والمتصفح وعنوان IP والأوقات والتفاعلات والسجلات التشخيصية وإشارات الاحتيال أو إساءة الاستخدام.', 'الأوامر والرسائل والملفات المرفوعة والوسائط المرجعية والمحتوى الناتج والإعدادات عندما تختار إرسالها أو حفظها.'] },
      { title: '3. كيفية استخدام المعلومات', paragraphs: ['نستخدم المعلومات لتقديم الخدمة وتخصيصها، ومصادقة المستخدمين، وتنفيذ مهام الذكاء الاصطناعي المطلوبة، وحفظ العمل عند تفعيل ذلك، وتقديم الدعم، ومراقبة الاعتمادية، ومنع الاحتيال والإساءة، والامتثال للالتزامات، وتحسين VANTRA. لا نستخدم بيانات Google Sign-In لأغراض لا تتعلق بالمصادقة وتشغيل الحساب.'] },
      { title: '4. محتوى الذكاء الاصطناعي ومقدمو الخدمات', paragraphs: ['عند طلب ميزة ذكاء اصطناعي، قد تُرسل الأوامر والملفات والإعدادات اللازمة إلى جهات تعالج الطلب لصالح VANTRA. لا نفصح إلا عما يلزم بشكل معقول ونلزم مقدمي الخدمة بالواجبات التعاقدية والقانونية المعمول بها. لا ترسل مواد سرية أو حساسة أو مقيدة قانونياً ما لم تكن مخولاً بذلك.'] },
      { title: '5. المشاركة والإفصاح', paragraphs: ['قد نشارك المعلومات مع الجهات اللازمة للاستضافة والمصادقة والأمان والتحليلات والدعم ومعالجة الدفع عند توفره ومعالجة طلبات الذكاء الاصطناعي. وقد نفصح عنها إذا فرض القانون ذلك، أو لحماية المستخدمين والخدمة، أو ضمن إعادة تنظيم الأعمال. لا تبيع VANTRA المعلومات الشخصية مقابل المال.'] },
      { title: '6. الاحتفاظ والحذف', paragraphs: ['نحتفظ بالمعلومات للمدة اللازمة بشكل معقول للأغراض الموضحة، ومنها تقديم الخدمة والأمان والتدقيق وتسوية النزاعات والالتزامات القانونية. تختلف المدة حسب نوع البيانات ونشاط الحساب. يمكنك طلب حذف الحساب أو المعلومات الشخصية. قد تبقى بعض البيانات مؤقتاً في النسخ الاحتياطية أو تُحفظ للأمان ومنع الاحتيال والمحاسبة أو بموجب القانون.'] },
      { title: '7. الأمان', paragraphs: ['نستخدم تدابير تقنية وتنظيمية معقولة لحماية المعلومات. لا يوجد نظام آمن بالكامل، ولا تضمن VANTRA استحالة الوصول غير المصرح أو الفقد أو سوء الاستخدام. أنت مسؤول عن حماية بيانات الدخول وإبلاغنا عند الاشتباه باختراق الحساب.'] },
      { title: '8. حقوقك وخياراتك', paragraphs: ['وفقاً للقانون المطبق، قد يحق لك طلب الوصول أو التصحيح أو الحذف أو التقييد أو الاعتراض على بعض المعالجة، وطلب نسخة قابلة للنقل، وسحب الموافقة، أو تقديم شكوى لجهة مختصة. قد نحتاج للتحقق من هويتك. ويمكنك إدارة اللغة والجلسات من خلال الخدمة أو المتصفح.'] },
      { title: '9. التغييرات والتواصل', paragraphs: ['قد نحدّث هذه السياسة مع تطور VANTRA. سنقدم إشعاراً مناسباً بالتغييرات الجوهرية عندما يلزم. للأسئلة أو طلبات الخصوصية: privacy@joinvantra.com.'] },
    ] },
    terms: { label: 'الشروط', title: 'شروط الاستخدام', description: 'القواعد التي تنطبق عند الوصول إلى VANTRA أو استخدامها.', updated: '8 سبتمبر 2026', sections: [
      { title: '1. القبول والأهلية', paragraphs: ['باستخدام VANTRA فإنك توافق على هذه الشروط. إذا كنت تستخدمها نيابة عن شخص أو جهة، فأنت تؤكد امتلاكك الصلاحية لإلزامها. ويجب أن تكون مؤهلاً قانونياً لإبرام هذه الاتفاقية وفق القانون المطبق.'] },
      { title: '2. الحسابات', paragraphs: ['يجب تقديم معلومات صحيحة وحماية بيانات الدخول وإبلاغ VANTRA سريعاً بأي وصول مشتبه به. أنت مسؤول عن نشاط حسابك إلا بقدر ما ينتج عن إخلال VANTRA بالتزاماتها. لا يجوز بيع الحساب أو نقله أو مشاركته بطريقة تضر بالأمان أو تخالف هذه الشروط.'] },
      { title: '3. خدمات الذكاء الاصطناعي ودقتها', paragraphs: ['تتيح VANTRA أدوات للدردشة والصور والفيديو وخدمات مرتبطة عند توفرها. قد تكون النتائج غير دقيقة أو ناقصة أو متحيزة أو مسيئة أو غير مناسبة. وهي ليست نصيحة قانونية أو طبية أو مالية أو مهنية. يجب مراجعتها قبل الاعتماد عليها أو نشرها أو اتخاذ قرار بناءً عليها. لا تضمن VANTRA نتيجة محددة أو توفر نموذج أو سرعة استجابة أو خدمة بلا انقطاع.'] },
      { title: '4. محتواك والمحتوى الناتج', paragraphs: ['تحتفظ بحقوقك السابقة في المحتوى الذي ترسله. وتمنح VANTRA ترخيصاً محدوداً وعالمياً لاستضافته ومعالجته ونسخه ونقله وعرضه فقط لتقديم الخدمة وتأمينها وتحسينها أو الامتثال للقانون. بينك وبين VANTRA، وبالقدر الذي يسمح به القانون، يمكنك استخدام المحتوى الناتج وفق هذه الشروط وقيود الأطراف الأخرى. لا تضمن VANTRA أن يكون المحتوى الناتج قابلاً للحماية أو فريداً أو خالياً من التعدي أو قابلاً للملكية الحصرية.'] },
      { title: '5. الاستخدام المحظور', paragraphs: ['يحظر استخدام VANTRA لانتهاك القانون أو حقوق الغير، أو إنشاء برمجيات ضارة، أو استغلال الناس أو خداعهم، أو إنتاج محتوى جنسي أو عنيف غير قانوني، أو انتحال الهوية، أو تسهيل الاحتيال، أو تجاوز وسائل الحماية، أو تعطيل الخدمة، أو اختبار الأنظمة دون إذن، أو استخراج الخدمة وإعادة بيعها دون موافقة كتابية، أو إرسال محتوى لا تملك حق استخدامه.'] },
      { title: '6. تغييرات الخدمة ومقدميها', paragraphs: ['يجوز لـVANTRA إضافة الميزات أو النماذج أو الجهات المقدمة أو الحدود أو طرق الوصول أو تعديلها أو تعليقها أو إزالتها. وقد تغيّر الجهات الخارجية خدماتها أو توقفها خارج سيطرة VANTRA. قد تحدث صيانة أو أعطال أو تأخير أو قيود سعة أو فقد للبيانات. سنحاول الإبلاغ عن التغييرات المهمة عندما يكون ذلك عملياً.'] },
      { title: '7. التعليق والإنهاء', paragraphs: ['يجوز لـVANTRA تقييد الوصول أو تعليقه أو إنهاؤه لمعالجة مخالفة أو خطر أمني أو احتيال أو عدم دفع أو متطلب قانوني أو ضرر أو خطر تشغيلي جوهري. يمكنك التوقف عن استخدام VANTRA في أي وقت. تبقى الأحكام التي تستمر بطبيعتها نافذة بعد الإنهاء.'] },
      { title: '8. الملكية الفكرية', paragraphs: ['تحتفظ VANTRA ومرخصوها بحقوق الخدمة والبرنامج والواجهة والعلامة والوثائق والمواد الأخرى، باستثناء محتواك. لا تمنحك الشروط حقوقاً في أسماء VANTRA أو شعاراتها أو تقنياتها خارج حق الاستخدام المحدود. ويمكن استخدام الملاحظات دون قيد أو مقابل مع عدم كشف هويتك علناً دون إذن.'] },
      { title: '9. إخلاء الضمانات', paragraphs: ['إلى أقصى حد يسمح به القانون، تُقدم VANTRA «كما هي» و«حسب التوفر». وتُستبعد الضمانات الضمنية، بما فيها القابلية للتسويق والملاءمة لغرض معين وعدم التعدي. ولا يستبعد شيء حقوقاً أو ضمانات لا يسمح القانون باستبعادها.'] },
      { title: '10. تحديد المسؤولية', paragraphs: ['إلى أقصى حد يسمح به القانون، لا تتحمل VANTRA الأضرار غير المباشرة أو العرضية أو الخاصة أو التبعية أو العقابية، ولا خسارة الأرباح أو الإيرادات أو البيانات أو السمعة أو الفرص. لا تتجاوز المسؤولية الإجمالية المبلغ الذي دفعته إلى VANTRA خلال الاثني عشر شهراً السابقة للواقعة، أو أي حد أدنى أعلى يفرضه القانون.'] },
      { title: '11. القوة القاهرة', paragraphs: ['لا تتحمل VANTRA التأخير أو الإخفاق الناتج عن أحداث خارجة عن السيطرة المعقولة، ومنها الكوارث وانقطاع الإنترنت أو الكهرباء والهجمات الإلكترونية والنزاعات العمالية والإجراءات الحكومية والحروب والاضطرابات والأوبئة وفشل البنية أو مقدمي الخدمات.'] },
      { title: '12. تعديل الشروط', paragraphs: ['قد نحدّث الشروط لتعكس تغييرات الخدمة أو القانون أو الأمان أو التشغيل. سننشر النسخة الجديدة بتاريخ محدّث، ونقدم إشعاراً إضافياً أو نطلب موافقة جديدة عندما يلزم. استمرار الاستخدام بعد سريان التحديث يعني القبول، إلا إذا تطلب القانون شكلاً آخر.'] },
    ] },
    billing: { label: 'الفوترة', title: 'سياسة الفوترة والاشتراكات والأرصدة', description: 'كيفية عمل الخطط المدفوعة والتجديد والإلغاء والاسترداد وأرصدة VANTRA عند توفرها.', updated: '8 سبتمبر 2026', sections: [
      { title: '1. النطاق ومعلومات الشراء', paragraphs: ['تنطبق هذه السياسة على الاشتراكات وشراء الأرصدة والخدمات المدفوعة الأخرى عند توفرها. يُعد السعر والعملة والفترة والأرصدة والحدود والضرائب وشروط التجديد المعروضة عند الدفع جزءاً من الشراء. ولا تجعل هذه السياسة ميزة مدفوعة غير متوفرة متاحة.'] },
      { title: '2. الاشتراكات والتجديد', paragraphs: ['يبدأ الاشتراك عند قبول الدفع. إذا أوضحت صفحة الدفع أن الاشتراك يتجدد تلقائياً، فسيتجدد للفترة المعلنة بالسعر الساري حينها حتى الإلغاء. تقدم VANTRA معلومات وإشعارات التجديد التي يفرضها القانون. وأنت مسؤول عن تحديث بيانات الدفع.'] },
      { title: '3. الإلغاء', paragraphs: ['يمكنك إلغاء الاشتراك عبر أدوات الحساب المتاحة أو قناة الدعم. ما لم تعرض صفحة الدفع أو يفرض القانون غير ذلك، يمنع الإلغاء التجديدات المقبلة ويسري في نهاية الفترة المدفوعة، وقد تستمر المزايا حتى ذلك الوقت. حذف الحساب لا يسوي تلقائياً الرسوم أو النزاعات القائمة.'] },
      { title: '4. أرصدة VANTRA', paragraphs: ['الأرصدة حق تعاقدي محدود لاستخدام الميزات المؤهلة، وليست نقوداً أو قيمة مخزنة أو حساباً بنكياً أو أصلاً قابلاً للتحويل، ولا قيمة نقدية لها إلا حيث يفرض القانون. قد تعرض الخدمة تكلفة تقديرية أو مؤكدة قبل الطلب، وقد يختلف الاستهلاك حسب النموذج أو نوع الوسائط أو الإعدادات أو النتيجة. الرصيد المتاح هو الرصيد المعروض في حسابك.'] },
      { title: '5. عمليات الإنشاء الفاشلة أو الملغاة', paragraphs: ['لا تقصد VANTRA عموماً خصم أرصدة لعملية تفشل قبل إنتاج نتيجة قابلة للاستخدام. قد يظهر حجز مؤقت أثناء المعالجة ثم يُحرر أو يُسوّى بعد الفشل أو الإلغاء. إذا بقي الخصم بسبب خطأ تقني فيمكنك طلب مراجعته. وقد تُعامل إساءة الاستخدام أو الإلغاء المتعمد المتكرر أو التكاليف التي تحققت فعلاً وفق ما تعرضه الميزة وبما يسمح به القانون.'] },
      { title: '6. المبالغ المستردة', paragraphs: ['تكون المدفوعات نهائية عموماً بعد استخدام الأرصدة أو مزايا الخدمة المدفوعة، باستثناء ما يفرضه القانون أو عندما تعرض VANTRA استرداداً صريحاً. وقد تراعي الأهلية تقديم الخدمة والاستخدام والخصم المكرر والفشل التقني والاحتيال وقواعد وسيلة الدفع. لا تحد هذه السياسة من حقوق المستهلك الإلزامية.'] },
      { title: '7. تغييرات الأسعار والحدود', paragraphs: ['يجوز لـVANTRA تغيير الأسعار المستقبلية أو تكلفة الأرصدة أو مزايا الخطط أو حدود الاستخدام. لا يغيّر ذلك شراءً مكتملاً بأثر رجعي إلا بموجب القانون أو لتصحيح خطأ واضح. وتُعلن تغييرات التجديد التلقائي مسبقاً حيث يلزم، ويمكنك الإلغاء قبل سريانها.'] },
      { title: '8. فشل الدفع والنزاعات والاحتيال', paragraphs: ['عند فشل الدفع، يجوز لـVANTRA إعادة المحاولة إذا كان ذلك مصرحاً، أو تقييد الميزات المدفوعة أو تعليق الاشتراك. تواصل مع VANTRA قبل الاعتراض البنكي لإتاحة التحقيق. قد يؤدي الدفع الاحتيالي أو الاعتراض المسيء أو التحايل أو إساءة استخدام الأرصدة إلى التعليق أو سحب الأرصدة المحصلة بغير حق أو تحصيل المبالغ المستحقة قانوناً أو الإبلاغ للجهات المختصة.'] },
      { title: '9. الأرصدة غير المستخدمة', paragraphs: ['تخضع صلاحية الأرصدة وترحيلها وتخصيصها للقواعد المعروضة للخطة أو الشراء عند الدفع. وما لم يُذكر صراحة، لا يمكن تحويلها أو استبدالها بنقود. لن تضع VANTRA قاعدة انتهاء أو تغيّرها سراً بعد الشراء، مع مراعاة القانون وهذه السياسة.'] },
      { title: '10. الإغلاق الدائم للخدمة', paragraphs: ['إذا أوقفت VANTRA خدمة مدفوعة نهائياً، فستبذل جهداً معقولاً لتقديم إشعار مسبق حيثما أمكن. تُعامل مدة الخدمة المدفوعة أو الأرصدة المشتراة غير المستخدمة وفق شروط الشراء والقانون الإلزامي، وقد يشمل ذلك فترة انتقال أو قيمة بديلة أو رصيد حساب أو استرداداً حيث يلزم.'] },
    ] },
  },
};
