import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: 'new', args: ['--no-sandbox'] });
const p = await b.newPage();
await p.setViewport({ width: 1500, height: 950 });
await p.goto('http://localhost:3000/studio', { waitUntil: 'networkidle2', timeout: 60000 });
await new Promise(r => setTimeout(r, 2200));
const out = {};
out.chatShaderMounts = await p.evaluate(() => document.querySelectorAll('.shader-container-exploded canvas').length);
out.chatAriaSend = await p.evaluate(() => [...document.querySelectorAll('button[aria-label="Send"]')].length);
await p.evaluate(() => [...document.querySelectorAll('aside button')].find(b => b.textContent.trim() === 'Motion Studio')?.click());
await new Promise(r => setTimeout(r, 1100));
out.motionShaderMounts = await p.evaluate(() => document.querySelectorAll('.shader-container-exploded canvas').length);
out.motionAriaGenerate = await p.evaluate(() => [...document.querySelectorAll('button[aria-label="Generate"]')].length);
console.log(JSON.stringify(out, null, 2));
await b.close();
