export const aiModels = [
  {
    id: "llama-3-3-70b:free",
    name: "Llama 3.3 70B Instruct (Free)",
    provider: "Meta AI",
    category: "chat",
    superpower: "100% Free Open-Weights Intelligence",
    icon: "fa-bolt",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "100% FREE",
    badgeType: "free",
    arabicDarjaScore: "96%",
    contextWindow: "128,000 Tokens",
    desc: {
      en: "Meta's flagship open-weights model delivering near-GPT-4o performance on general reasoning, coding, and multilingual conversation at 0 cost.",
      fr: "Le modèle phare de Meta offrant des performances proches de GPT-4o pour le raisonnement, le code et les conversations, 100% gratuit.",
      ar: "النموذج المجاني الرائد من Meta، يقدم أداءً فائقاً يقارع GPT-4o في البرمجة، التفكير المنطقي، ودعم اللغة العربية مجاناً بالكامل."
    },
    capabilities: ["100% Free (0 pts)", "Coding & Logic", "128k Context", "Fast Latency"],
    samplePrompt: "Explain how to build a Next.js server action with Supabase authentication.",
    costPts: "0 pts (FREE)"
  },
  {
    id: "deepseek-r1:free",
    name: "DeepSeek R1 (Free Tier)",
    provider: "DeepSeek AI",
    category: "chat",
    superpower: "Mathematical Reasoning & Logic",
    icon: "fa-network-wired",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "100% FREE",
    badgeType: "free",
    arabicDarjaScore: "97%",
    contextWindow: "64,000 Tokens",
    desc: {
      en: "State-of-the-art open reasoning engine outperforming proprietary models on complex math, science, and algorithmic problem solving at 0 cost.",
      fr: "Moteur de raisonnement ouvert d'élite surpassant les modèles propriétaires sur les mathématiques et le code, 100% gratuit.",
      ar: "عملاق التفكير المنطقي والرياضيات المتقدمة وحل المسائل البرمجية المعقدة، متاح مجاناً لجميع المستخدمين."
    },
    capabilities: ["100% Free (0 pts)", "Math Olympiad", "Chain-of-Thought", "Algorithm Design"],
    samplePrompt: "Write a high-performance sorting algorithm in Python with asymptotic analysis.",
    costPts: "0 pts (FREE)"
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    category: "chat",
    superpower: "#1 Coding & Deep Reasoning",
    icon: "fa-brain",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Flagship LLM",
    badgeType: "hot",
    arabicDarjaScore: "99%",
    contextWindow: "200,000 Tokens",
    desc: {
      en: "State-of-the-art reasoning, software engineering, complex data analysis and natural Algerian Darja comprehension.",
      fr: "Raisonnement de pointe, ingénierie logicielle, analyse de données complexes et excellente compréhension de la Darija algérienne.",
      ar: "النموذج الأقوى عالمياً في البرمجة، التفكير المنطقي المعقد، وكتابة المحتوى بالدارجة الجزائرية والعربية الفصحى."
    },
    capabilities: ["Python / TypeScript", "Darja Fluent", "200k Context", "Visual Artifacts"],
    samplePrompt: "Write a high-converting marketing plan for an Algerian e-commerce shop with BaridiMob checkout flow.",
    costPts: "25 pts / request"
  },
  {
    id: "flux-1-pro",
    name: "Flux.1 Pro",
    provider: "Black Forest Labs",
    category: "image",
    superpower: "Photorealism & Typography",
    icon: "fa-palette",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Ultra-HD Image",
    badgeType: "trending",
    arabicDarjaScore: "Visual",
    contextWindow: "4K Resolution",
    desc: {
      en: "The undisputed champion of AI photorealism, skin textures, atmospheric lighting and accurate readable text in images.",
      fr: "Le champion incontesté du photoréalisme, des textures de peau et du rendu de texte lisible dans les images.",
      ar: "بطل الواقعية الفوتوغرافية وتوليد النصوص المكتوبة بوضوح تام داخل الصور مع إضاءة سينمائية وتفاصيل 4K."
    },
    capabilities: ["Accurate In-Image Text", "Skin Texture 4K", "Cinematic Optics", "Fast Render"],
    samplePrompt: "Cinematic shot of a modern creative workspace in Algiers with sunset golden hour lighting, 8k photo.",
    costPts: "60 pts / image"
  },
  {
    id: "kling-ai-1-5",
    name: "Kling AI 1.5 HD",
    provider: "Kuaishou",
    category: "video",
    superpower: "Realistic Physics & 1080p Motion",
    icon: "fa-video",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Cinematic Video",
    badgeType: "hot",
    arabicDarjaScore: "Video",
    contextWindow: "10s High-Motion",
    desc: {
      en: "Creates realistic 1080p video clips with authentic real-world physics, fluid character motion, and dramatic camera pans.",
      fr: "Crée des vidéos 1080p réalistes avec une physique fluide et des mouvements de caméra spectaculaires.",
      ar: "صناعة مقاطع فيديو فائقة الواقعية بدقة 1080p مع محاكاة فيزيائية حقيقية لحركة الأجسام والأشخاص وزوايا الكاميرا."
    },
    capabilities: ["1080p 60fps", "Real Physics", "Complex Motion", "10-Sec Duration"],
    samplePrompt: "Drone shot gliding over the Mediterranean coastline of Tipaza at sunrise, cinematic lighting.",
    costPts: "240 pts / 5s video"
  },
  {
    id: "gpt-4o",
    name: "GPT-4o (Omni)",
    provider: "OpenAI",
    category: "chat",
    superpower: "Fast Multimodal & Real-time Vision",
    icon: "fa-sparkles",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Multimodal King",
    badgeType: "popular",
    arabicDarjaScore: "98%",
    contextWindow: "128,000 Tokens",
    desc: {
      en: "Flagship multimodal intelligence from OpenAI. Handles text, charts, diagrams, and voice with lightning-fast latency.",
      fr: "Intelligence multimodale de référence d'OpenAI. Traite le texte, les diagrammes et les images à vitesse éclair.",
      ar: "النموذج المتعدد الوسائط الرائد من OpenAI، يحلل الصور والمستندات والرسوم البيانية ويجيب بسرعة فائقة بالعربية والإنجليزية."
    },
    capabilities: ["Vision Analysis", "Web Browsing", "Fast Latency", "Audio Processing"],
    samplePrompt: "Analyze this financial spreadsheet and highlight key growth metrics for Q3.",
    costPts: "20 pts / request"
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1 / V3",
    provider: "DeepSeek AI",
    category: "chat",
    superpower: "Open-Weights Reasoning Champ",
    icon: "fa-network-wired",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Reasoning Giant",
    badgeType: "trending",
    arabicDarjaScore: "97%",
    contextWindow: "64,000 Tokens",
    desc: {
      en: "Revolutionary mathematical logic and open reasoning engine outperforming proprietary models at high token efficiency.",
      fr: "Raisonnement mathématique et logique de nouvelle génération rivalisant avec les plus grands modèles propriétaires.",
      ar: "عملاق التفكير المنطقي والرياضي الثوري، يتفوق في حل المسائل المعقدة، خوارزميات البرمجة، والبحث العلمي."
    },
    capabilities: ["Chain-of-Thought", "Math Olympiad", "Algorithm Design", "Cost Efficient"],
    samplePrompt: "Prove this mathematical theorem step-by-step and write a Python benchmark simulation.",
    costPts: "10 pts / request"
  },
  {
    id: "midjourney-v6-1",
    name: "Midjourney v6.1",
    provider: "Midjourney",
    category: "image",
    superpower: "Aesthetic Mastery & Visual Drama",
    icon: "fa-wand-magic-sparkles",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Artistic Genius",
    badgeType: "popular",
    arabicDarjaScore: "Visual",
    contextWindow: "Creative Art",
    desc: {
      en: "Unmatched artistic direction, cinematic concept art, commercial fashion photography and surreal visual storytelling.",
      fr: "Direction artistique inégalée, concept art cinématographique et photographie de mode haut de gamme.",
      ar: "المرجع العالمي الأول في الإبداع الفني، تصميم الشخصيات، الإعلانات التجارية الخلابة، والأعمال الفنية السينمائية."
    },
    capabilities: ["Cinematic Lighting", "Stylized Concept Art", "Fashion Photography", "Inpainting & Zoom"],
    samplePrompt: "Luxury perfume bottle resting on ancient Sahara desert dunes at dusk, golden mist, cinematic lighting.",
    costPts: "70 pts / render"
  },
  {
    id: "runway-gen-3",
    name: "Runway Gen-3 Alpha",
    provider: "Runway",
    category: "video",
    superpower: "Hollywood Camera & Scene Control",
    icon: "fa-film",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Studio Director",
    badgeType: "pro",
    arabicDarjaScore: "Video",
    contextWindow: "Cinematic 4K",
    desc: {
      en: "Industry-standard generative video for commercial filmmakers, music videos, visual effects and dynamic transitions.",
      fr: "Le standard de l'industrie pour les réalisateurs de cinéma, clips vidéo et effets visuels de haute précision.",
      ar: "معيار هوليوود لتوليد الفيديوهات السينمائية للمخرجين والمصممين، مع تحكم دقيق في حركة الكاميرا والإضاءة والبيئة."
    },
    capabilities: ["Camera Trajectory Control", "Motion Brush", "Visual FX", "Hyper-Realistic"],
    samplePrompt: "Fast tracking shot following a sports car zooming through an illuminated futuristic tunnel.",
    costPts: "280 pts / 5s cut"
  },
  {
    id: "elevenlabs-v2",
    name: "ElevenLabs Voice Studio",
    provider: "ElevenLabs",
    category: "audio",
    superpower: "Lifelike Voice & Accent Cloning",
    icon: "fa-microphone-lines",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Emotional Voice",
    badgeType: "trending",
    arabicDarjaScore: "96%",
    contextWindow: "32+ Accents",
    desc: {
      en: "Indistinguishable natural human speech synthesis, voice cloning, expressive podcast voiceovers and multi-lingual dubbing.",
      fr: "Synthèse vocale humaine d'un réalisme bluffant, clonage de voix et doublage multilingue expressif.",
      ar: "توليد أصوات بشرية طبيعية 100% مع نبرات انفعالية، دبلجة المقاطع، واستنساخ الأصوات باللغة العربية ومختلف اللهجات."
    },
    capabilities: ["Voice Cloning", "Emotion Modulation", "Arabic Accents", "Podcast Audio"],
    samplePrompt: "Voiceover for a documentary trailer about Algerian historical architecture with deep ambient tone.",
    costPts: "30 pts / min audio"
  },
  {
    id: "suno-ai-v3-5",
    name: "Suno AI v3.5",
    provider: "Suno",
    category: "audio",
    superpower: "Full Song & Music Production",
    icon: "fa-music",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Music Studio",
    badgeType: "hot",
    arabicDarjaScore: "Audio",
    contextWindow: "4-Minute Songs",
    desc: {
      en: "Generate full studio-grade radio tracks with vocals, instruments, lyrics and tailored musical genres in seconds.",
      fr: "Générez des chansons complètes avec voix de studio, instruments et paroles dans tous les genres musicaux.",
      ar: "إنتاج مقاطع وأغاني وموسيقى تصويرية كاملة مع الغناء والآلات الموسيقية وكلمات متناسقة بمختلف الأنواع الفنية."
    },
    capabilities: ["Full Song Generation", "Vocal & Instrumental", "Multi-Genre", "Radio Quality"],
    samplePrompt: "Upbeat electronic track with traditional Andalusian acoustic strings and modern punchy drums.",
    costPts: "45 pts / song"
  },
  {
    id: "gemini-1-5-pro",
    name: "Gemini 1.5 Pro",
    provider: "Google DeepMind",
    category: "chat",
    superpower: "2 Million Token Megacontext",
    icon: "fa-google",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Document Titan",
    badgeType: "popular",
    arabicDarjaScore: "98%",
    contextWindow: "2,000,000 Tokens",
    desc: {
      en: "Process entire video libraries, 1,000-page PDF books, audio recordings and massive codebases in a single prompt.",
      fr: "Traitez des livres entiers de 1 000 pages, des vidéos longues et des bases de code massives en un seul prompt.",
      ar: "قادر على قراءة واستيعاب كتب كاملة بأكثر من 1,000 صفحة، فيديوهات بساعات طويلة، ومكتبات برمجية ضخمة في طلب واحد."
    },
    capabilities: ["2M Token Context", "1-Hour Video Reading", "Book Summaries", "Multimodal QA"],
    samplePrompt: "Upload an entire legal contract or corporate financial archive for immediate audit and risk analysis.",
    costPts: "25 pts / request"
  },
  {
    id: "whisper-large-v3",
    name: "OpenAI Whisper HD",
    provider: "OpenAI",
    category: "audio",
    superpower: "Arabic & Darja Speech-to-Text",
    icon: "fa-file-audio",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "Transcription",
    badgeType: "pro",
    arabicDarjaScore: "99%",
    contextWindow: "Unlimited Audio",
    desc: {
      en: "Flawless speech recognition and subtitle generation for podcasts, phone calls, and videos in Algerian Darja and French.",
      fr: "Reconnaissance vocale parfaite et sous-titrage automatique pour podcasts et réunions en arabe et français.",
      ar: "التفريغ الصوتي الأكثر دقة للمحاضرات، المكالمات والبودكاست بالدارجة الجزائرية، العربية والفرنسية مع توقيت زمني دقيق."
    },
    capabilities: ["Darja Transcription", "Word Timestamps", "Noise Robustness", "99+ Languages"],
    samplePrompt: "Transcribe a 30-minute recorded meeting with mixed Darja, French, and English into structured bullet points.",
    costPts: "15 pts / 10 mins"
  },
  {
    id: "luma-dream-machine",
    name: "Luma Dream Machine",
    provider: "Luma AI",
    category: "video",
    superpower: "Ultra-Fast 3D Camera Pan",
    icon: "fa-cube",
    color: "#1FD8B8",
    bgGlow: "rgba(31, 216, 184, 0.08)",
    tag: "3D Motion",
    badgeType: "trending",
    arabicDarjaScore: "Video",
    contextWindow: "5s High-FPS",
    desc: {
      en: "High-frame-rate realistic camera movement through 3D environments, character consistency, and prompt fidelity.",
      fr: "Mouvements de caméra 3D ultra-fluides, fidélité aux prompts et consistance des personnages.",
      ar: "توليد مشاهد ثلاثية الأبعاد سريعة مع حركة كاميرا طليقة ومحافظة دقيقة على ملامح الشخصيات والبيئات."
    },
    capabilities: ["Keyframe Camera", "Rapid Rendering", "Character Consistency", "Dynamic Angles"],
    samplePrompt: "Smooth 360-degree orbit around an architect's modern villa model with interior warm lighting.",
    costPts: "220 pts / 5s cut"
  }
];
